// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybvaqrchmhxjewfqlupn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidmFxcmNobWh4amV3ZnFsdXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzU2MDEsImV4cCI6MjA2NTQ1MTYwMX0.NSwotERW7dQx7V6iL6cGj2hMNy5kTIMZXn2c5TDLD_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);